import Foundation

extension ToolCatalog {
  static var additions: [JSONValue] {
    let path = string("Normalized project-relative path")
    let tab = string("tabId returned by browser_session(action=open)", max: 80)
    let ref: [String: JSONValue] = ["tabId": tab, "snapshotId": string("Latest snapshotId, valid for 60s", max: 80), "ref": string("Exact semantic ref from that snapshot", max: 40)]
    let post: [String: JSONValue] = [
      "waitForText": string("Optional visible-text post-condition checked after the action executes once", max: 4096),
      "waitForUrlContains": string("Optional URL-substring post-condition checked after the action executes once", max: 4096),
      "waitForState": enumeration(["domcontentloaded", "load", "networkidle"]),
      "waitTimeoutMs": integer(100, 20_000, 5_000),
    ]
    return [
      tool("list_directory", "Bounded project tree. Lists protected names with protected=true but never traverses them. Never follows symlinks.", ["path": path, "depth": integer(1, 8, 1), "maxEntries": integer(1, 2000, 500), "includeHidden": flag(false)]),
      tool("read_image", "Return a native MCP image preview without desktop permissions. Original bytes are available separately through export_artifact.", ["path": path, "maxDimension": integer(320, 2048, 1600)], required: ["path"]),
      tool("export_artifact", "Export either one original project file or 1–20 project paths as an immutable ZIP ResourceLink. Provide exactly one of path or paths. Metadata includes SHA/createdAt/expiresAt; runtime stop or cache pressure may evict before the maximum TTL.", ["path": path, "paths": strings("Project-relative files/directories to package as ZIP", max: 20), "name": string("Optional ZIP artifact filename; .zip is added when omitted", max: 255)]),
      tool("import_artifact", "Save one unexpired Artifact issued by this project's runtime into a new project file, with an automatic recovery checkpoint. Never overwrites, executes or unpacks the file. Requires project:write and the source Artifact's read permission (project:read, process:run or browser:use). Accepts no URL, base64 or Host attachment without a verified adapter.", ["resource": string("Exact luti://artifact/ reference issued by this runtime", max: 256), "path": path, "dryRun": flag(false)], required: ["resource", "path"], readOnly: false),
      tool("path_action", "Project path mutation with automatic bounded recovery checkpoint. action=createDirectory/copy/move/delete. Tree mutations that cannot be checkpointed safely fail before mutation; copy/move never overwrite destinations.", ["action": enumeration(["createDirectory", "copy", "move", "delete"]), "path": path, "source": path, "destination": path, "recursive": flag(false)], required: ["action"], readOnly: false),
      tool("inspect_project", "Static project discovery without executing code. Prefer view=summary for one taskRegistry and scoped AGENTS/CLAUDE/Copilot instruction sources. Omitted view or full preserves the complete legacy projection and capabilityGraph.", ["path": path, "view": enumeration(["summary", "full"])]),
      tool("code_query", "Bounded short-lived LSP query requiring project:read, process:run and projectToken. Starts a local language-service process that may write caches or access the network; not a read-only sandbox. Swift uses Xcode SourceKit-LSP; TypeScript/JavaScript and Python use an already-installed project-local or developer-PATH language server. Luti never downloads one. Supports documentSymbols, definition, references, implementations and hover; pull diagnostics are currently Swift-only. Only project-root non-protected locations are returned.", ["path": path, "action": enumeration(["documentSymbols", "definition", "references", "implementations", "hover", "diagnostics"]), "line": integer(1, 1_000_000), "column": integer(1, 1_000_000), "includeDeclaration": flag(true), "maxResults": integer(1, 200, 100)], required: ["path", "action"], readOnly: false, openWorld: true),
      tool("skills", "Project Skill access. action=list discovers root .agents/.claude/.codex skills; action=read returns one discovered SKILL.md plus bounded support-file listing. Reading never executes instructions.", ["action": enumeration(["list", "read"]), "path": path], required: ["action"]),
      tool("browser_session", "Mutate owned browser sessions. action=open creates an isolated HTTP(S) tab; navigate changes one owned tab exactly once with optional post-condition; close closes one owned tab/context.", ["action": enumeration(["open", "navigate", "close"]), "tabId": tab, "url": string("HTTP(S) URL for open/navigate", max: 8192), "width": integer(320, 3840, 1440), "height": integer(240, 2400, 900)].merging(post, uniquingKeysWith: { _, b in b }), required: ["action"], readOnly: false, openWorld: true),
      tool("browser_observe", "Read browser state. action=tabs lists owned tabs; wait waits for one load/text/URL condition; snapshot returns semantic refs with optional subtree scoping; screenshot returns viewport/full-page or one semantic element as preview + PNG Artifact.", ["action": enumeration(["tabs", "wait", "snapshot", "screenshot"]), "tabId": tab, "state": enumeration(["domcontentloaded", "load", "networkidle"]), "text": string("Visible text substring for action=wait", max: 4096), "urlContains": string("URL substring for action=wait", max: 4096), "timeoutMs": integer(100, 20_000, 10_000), "scopeSnapshotId": string("Latest snapshotId for scoped observation", max: 80), "scopeRef": string("Semantic ref from scopeSnapshotId", max: 40), "depth": integer(1, 12, 12), "fullPage": flag(false)], required: ["action"], openWorld: true),
      tool("browser_action", "Perform one ordinary semantic page action exactly once. action=click/hover/fill/press/select/check. Uses the latest snapshot/ref; optional post-condition can verify text/URL/load state without replay.", ref.merging(["action": enumeration(["click", "hover", "fill", "press", "select", "check"]), "text": string("Text for fill; never enter secrets", max: 16_384), "key": string("Playwright key for press", max: 80), "value": string("Option value for select", max: 4096), "checked": flag(true)], uniquingKeysWith: { _, b in b }).merging(post, uniquingKeysWith: { _, b in b }), required: ["action", "tabId", "snapshotId", "ref"], readOnly: false, openWorld: true),
      tool("browser_transfer", "Transfer one file through the page. action=upload requires browser:use and project:read, stages one safe project file to a semantic file input and may use a post-condition; action=download clicks one semantic ref and returns a bounded immutable Artifact if a download is confirmed.", ref.merging(["action": enumeration(["upload", "download"]), "path": path], uniquingKeysWith: { _, b in b }).merging(post, uniquingKeysWith: { _, b in b }), required: ["action", "tabId", "snapshotId", "ref"], readOnly: false, openWorld: true),
      tool("browser_inspect", "Read bounded browser diagnostics. action=console returns console/page errors; networkErrors returns failed/HTTP>=400 requests; network returns the request timeline. Never returns credentials, headers, request or response bodies.", ["action": enumeration(["console", "networkErrors", "network"]), "tabId": tab, "limit": integer(1, 200, 100)], required: ["action", "tabId"], openWorld: true),
      tool("browser_dialog", "Handle one pending JavaScript dialog explicitly exactly once. Dialogs are never auto-accepted. Optional post-condition verifies the page state after accept/dismiss without replaying the dialog action.", ["tabId": tab, "dialogId": string("Pending dialogId returned by browser_observe(action=snapshot) or the triggering browser_action", max: 80), "action": enumeration(["accept", "dismiss"]), "promptText": string("Optional prompt text; valid only with action=accept. Never enter secrets.", max: 4096)].merging(post, uniquingKeysWith: { _, b in b }), required: ["tabId", "dialogId", "action"], readOnly: false, openWorld: true),
      tool("browser_evaluate", "Evaluate JavaScript in an owned webpage, not the host Node process. May mutate page or make network requests; requires local execution consent. Returns bounded JSON.", ["tabId": tab, "expression": string("JavaScript expression or function", max: 16_384)], required: ["tabId", "expression"], readOnly: false, openWorld: true),

    ]
  }
}
